### ISSUE TITLE
Wolrd Downloader doesn't download paintings

### ISSUE THREAD

**Issue by badwolfboy** [uyjulian/LiteModWDL#4] opened 2015-12-22 19:01 UTC

**Comment by Pokechu22** [comment] 2015-12-22 19:02
Does it not?  Hm.  I thought it did.  I'll go check.

**Comment by badwolfboy** [comment] 2015-12-22 19:03
I tried to download Hogwarts from mc.nerdcrafteria.com. It worked well, apart from the fact that it didn't downloaded any of the paintings, that hided all the secret passages. The fire, that did not spread on the server, began to spread in the downloaded world.

**Comment by Pokechu22** [comment] 2015-12-22 19:20
OK, I've managed to reproduce the painting issue.  It's odd.

Basically, it _does_ save them, but for whatever reason after it saves them once, they disappear clientside.  So if you start downloading a second time without reloading the chunks, then the paintings aren't saved (since they're no longer there).  I'll look into why they're getting removed.

As for the fire, you'll need to either quickly run `/gamerule doFireTick false` quickly or use [the fire and ice mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286894-1-8-8-1-8-1-7-10-1-7-2-1-6-4-etc-updated-fire-and), which disabled fire spread and ice melting.

**Comment by badwolfboy** [comment] 2015-12-22 19:32
Thank you! I'll look forward to see one of the best mods get perfect :-)

**Comment by Pokechu22** [comment] 2015-12-22 20:06
Well, I found where the paintings are going...

![Below the world o_o](https://cloud.githubusercontent.com/assets/8334194/11964698/530be384-a8a4-11e5-96b4-f0fc55a72004.png)

Now to figure out why.

**Comment by Pokechu22** [comment] 2015-12-22 20:43
The entities are definitely getting moved as WDL saves the chunk they are in.

<pre height="10em">
[12:33:58] [Client thread/INFO]: EntitySquid['Squid'/3700, l='MpServer', x=-41.88, y=56.28, z=26.47] -41.875 56.28125 26.46875
[12:33:58] [Client thread/INFO]: EntitySpider['Spider'/3707, l='MpServer', x=-29.50, y=22.00, z=-36.50] -29.5 22.0 -36.5
[12:33:58] [Client thread/INFO]: EntityBat['Bat'/3682, l='MpServer', x=4.78, y=22.00, z=-43.75] 4.78125 22.0 -43.75
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3651, l='MpServer', x=-45.50, y=27.00, z=-9.50] -45.5 27.0 -9.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3679, l='MpServer', x=-2.50, y=25.00, z=-47.50] -2.5 25.0 -47.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3652, l='MpServer', x=-46.50, y=21.00, z=-8.50] -46.5 21.0 -8.5
[12:33:58] [Client thread/INFO]: EntityPlayerSP['Player203'/3155, l='MpServer', x=-0.74, y=64.00, z=-0.52] -0.7415043093022524 64.0 -0.5244893510341058
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3628, l='MpServer', x=-2.03, y=65.00, z=-2.50] -2.03125 65.0 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3629, l='MpServer', x=-1.50, y=66.50, z=-3.03] -1.5 66.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3630, l='MpServer', x=-2.03, y=67.50, z=-2.50] -2.03125 67.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3631, l='MpServer', x=-1.50, y=67.50, z=-3.03] -1.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3632, l='MpServer', x=-0.50, y=67.50, z=-3.03] -0.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3633, l='MpServer', x=-0.97, y=64.50, z=-2.50] -0.96875 64.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3634, l='MpServer', x=-0.50, y=67.50, z=-1.97] -0.5 67.5 -1.96875
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3635, l='MpServer', x=-0.97, y=66.50, z=-2.50] -0.96875 66.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3636, l='MpServer', x=0.50, y=67.50, z=-3.03] 0.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3637, l='MpServer', x=1.50, y=67.50, z=-3.03] 1.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3638, l='MpServer', x=1.50, y=66.50, z=-3.03] 1.5 66.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3639, l='MpServer', x=1.50, y=64.50, z=-3.03] 1.5 64.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3640, l='MpServer', x=2.03, y=65.50, z=-2.50] 2.03125 65.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3641, l='MpServer', x=2.03, y=66.50, z=-2.50] 2.03125 66.5 -2.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=-1, y=128, z=-1}
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3642, l='MpServer', x=2.03, y=67.50, z=-2.50] 2.03125 67.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3643, l='MpServer', x=1.00, y=67.50, z=-1.97] 1.0 67.5 -1.96875
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3644, l='MpServer', x=0.97, y=64.50, z=-2.50] 0.96875 64.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3645, l='MpServer', x=0.97, y=66.00, z=-2.50] 0.96875 66.0 -2.5
[12:33:58] [Client thread/INFO]: EntitySquid['Squid'/3646, l='MpServer', x=37.66, y=58.34, z=16.69] 37.65625 58.34375 16.6875
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Old TE does not need importing: Sign (net.minecraft.tileentity.TileEntitySign) at BlockPos{x=-5, y=30, z=-5} 
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3648, l='MpServer', x=-41.50, y=63.00, z=47.50] -41.5 63.0 47.5
[12:33:58] [Client thread/INFO]: EntityEnderman['Enderman'/3649, l='MpServer', x=-41.50, y=27.00, z=0.50] -41.5 27.0 0.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3650, l='MpServer', x=-42.09, y=27.00, z=-6.34] -42.09375 27.0 -6.34375
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3653, l='MpServer', x=-38.50, y=20.00, z=-1.50] -38.5 20.0 -1.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=-1, y=63, z=-1}
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3654, l='MpServer', x=-40.50, y=27.00, z=-5.50] -40.5 27.0 -5.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3655, l='MpServer', x=-44.50, y=36.00, z=-1.50] -44.5 36.0 -1.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3656, l='MpServer', x=-37.50, y=23.00, z=-26.50] -37.5 23.0 -26.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3664, l='MpServer', x=12.50, y=10.00, z=-30.50] 12.5 10.0 -30.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3677, l='MpServer', x=-35.50, y=27.00, z=-45.50] -35.5 27.0 -45.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3678, l='MpServer', x=-43.50, y=20.00, z=-35.50] -43.5 20.0 -35.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3680, l='MpServer', x=-2.50, y=25.00, z=-45.50] -2.5 25.0 -45.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=128, z=1}
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3681, l='MpServer', x=1.50, y=23.00, z=-44.50] 1.5 23.0 -44.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3683, l='MpServer', x=25.50, y=21.00, z=-44.50] 25.5 21.0 -44.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3684, l='MpServer', x=34.50, y=31.00, z=-45.50] 34.5 31.0 -45.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Chest (net.minecraft.tileentity.TileEntityChest) at BlockPos{x=0, y=128, z=1}
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3685, l='MpServer', x=34.50, y=27.00, z=-43.50] 34.5 27.0 -43.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3686, l='MpServer', x=45.50, y=32.00, z=-37.50] 45.5 32.0 -37.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3687, l='MpServer', x=42.50, y=32.00, z=-42.50] 42.5 32.0 -42.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3688, l='MpServer', x=33.50, y=32.00, z=-45.50] 33.5 32.0 -45.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Old TE does not need importing: Control (net.minecraft.tileentity.TileEntityCommandBlock) at BlockPos{x=0, y=63, z=1} 
[12:33:58] [Client thread/INFO]: EntitySquid['Squid'/3700, l='MpServer', x=-41.88, y=56.28, z=26.47] -41.875 56.28125 26.46875
[12:33:58] [Client thread/INFO]: EntitySpider['Spider'/3707, l='MpServer', x=-29.50, y=22.00, z=-36.50] -29.5 22.0 -36.5
[12:33:58] [Client thread/INFO]: EntityBat['Bat'/3682, l='MpServer', x=4.67, y=22.05, z=-43.90] 4.666666666666667 22.052083333333332 -43.895833333333336
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3651, l='MpServer', x=-45.50, y=27.00, z=-9.50] -45.5 27.0 -9.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3679, l='MpServer', x=-2.50, y=25.00, z=-47.50] -2.5 25.0 -47.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=63, z=1}
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3652, l='MpServer', x=-46.50, y=21.00, z=-8.50] -46.5 21.0 -8.5
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Old TE does not need importing: Control (net.minecraft.tileentity.TileEntityCommandBlock) at BlockPos{x=0, y=63, z=0} 
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=128, z=0}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Chest (net.minecraft.tileentity.TileEntityChest) at BlockPos{x=0, y=128, z=0}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=63, z=0}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=63, z=2}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=1, y=128, z=2}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=0, y=128, z=2}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Beacon (net.minecraft.tileentity.TileEntityBeacon) at BlockPos{x=0, y=63, z=2}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Old TE does not need importing: MobSpawner (net.minecraft.tileentity.TileEntityMobSpawner) at BlockPos{x=-113, y=11, z=-108} 
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Using old TE from saved file: Chest (net.minecraft.tileentity.TileEntityChest) at BlockPos{x=-117, y=24, z=-112}
[12:33:58] [WDL Save Thread/INFO]: [WorldDL] Old TE does not need importing: Control (net.minecraft.tileentity.TileEntityCommandBlock) at BlockPos{x=-56, y=57, z=-40} 
[12:33:58] [Client thread/INFO]: EntityPlayerSP['Player203'/3155, l='MpServer', x=-0.74, y=64.00, z=-0.52] -0.7415043093022524 64.0 -0.5244893510341058
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3628, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3629, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3630, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3631, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3632, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3633, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3634, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3635, l='MpServer', x=0.00, y=0.00, z=0.00] 0.0 0.0 0.0
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3636, l='MpServer', x=0.50, y=67.50, z=-3.03] 0.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3637, l='MpServer', x=1.50, y=67.50, z=-3.03] 1.5 67.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3638, l='MpServer', x=1.50, y=66.50, z=-3.03] 1.5 66.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3639, l='MpServer', x=1.50, y=64.50, z=-3.03] 1.5 64.5 -3.03125
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3640, l='MpServer', x=2.03, y=65.50, z=-2.50] 2.03125 65.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3641, l='MpServer', x=2.03, y=66.50, z=-2.50] 2.03125 66.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3642, l='MpServer', x=2.03, y=67.50, z=-2.50] 2.03125 67.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3643, l='MpServer', x=1.00, y=67.50, z=-1.97] 1.0 67.5 -1.96875
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3644, l='MpServer', x=0.97, y=64.50, z=-2.50] 0.96875 64.5 -2.5
[12:33:58] [Client thread/INFO]: EntityPainting['Painting'/3645, l='MpServer', x=0.97, y=66.00, z=-2.50] 0.96875 66.0 -2.5
[12:33:58] [Client thread/INFO]: EntitySquid['Squid'/3646, l='MpServer', x=37.66, y=58.34, z=16.69] 37.65625 58.34375 16.6875
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3648, l='MpServer', x=-41.50, y=63.00, z=47.50] -41.5 63.0 47.5
[12:33:58] [Client thread/INFO]: EntityEnderman['Enderman'/3649, l='MpServer', x=-41.50, y=27.00, z=0.50] -41.5 27.0 0.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3650, l='MpServer', x=-42.09, y=27.00, z=-6.34] -42.09375 27.0 -6.34375
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3653, l='MpServer', x=-38.50, y=20.00, z=-1.50] -38.5 20.0 -1.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3654, l='MpServer', x=-40.50, y=27.00, z=-5.50] -40.5 27.0 -5.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3655, l='MpServer', x=-44.50, y=36.00, z=-1.50] -44.5 36.0 -1.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3656, l='MpServer', x=-37.50, y=23.00, z=-26.50] -37.5 23.0 -26.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3664, l='MpServer', x=12.50, y=10.00, z=-30.50] 12.5 10.0 -30.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3677, l='MpServer', x=-35.50, y=27.00, z=-45.50] -35.5 27.0 -45.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3678, l='MpServer', x=-43.50, y=20.00, z=-35.50] -43.5 20.0 -35.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3680, l='MpServer', x=-2.50, y=25.00, z=-45.50] -2.5 25.0 -45.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3681, l='MpServer', x=1.50, y=23.00, z=-44.50] 1.5 23.0 -44.5
[12:33:58] [Client thread/INFO]: EntitySkeleton['Skeleton'/3683, l='MpServer', x=25.50, y=21.00, z=-44.50] 25.5 21.0 -44.5
[12:33:58] [Client thread/INFO]: EntityCreeper['Creeper'/3684, l='MpServer', x=34.50, y=31.00, z=-45.50] 34.5 31.0 -45.5
[12:33:58] [Client thread/INFO]: EntityZombie['Zombie'/3685, l='MpServer', x=34.50, y=27.00, z=-43.50] 34.5 27.0 -43.5
</pre>

Note how after WDL imports stuff in the given chunk, the paintings in that chunk are moved.  I suspect that this is the same thing that causes the world to sometimes go invisible.  I _think_ I know the code that is causing it.

**Comment by Pokechu22** [comment] 2015-12-22 21:34
I've fixed it in pokechu22/WorldDownloader@7184231c6218ca1d6ec6ccd6a5553bbaa23ea947.

Basically, due to boats being awesome (the same thing used to happen to squid and other mobs (especially when packed tightly)), I added a system where entities would be returned to their server positions when saved.

![](http://imgur.com/3QQchZL.gif)

However, I didn't factor in the fact that some entities had special spawn packets (mainly, paintings - [Packet 0x10](http://wiki.vg/index.php?title=Protocol&oldid=7121#Spawn_Painting)).  This means that the `serverPosX`, `serverPosY`, and `serverPosZ` were all 0 - the entity was teleported to 0,0,0.  The same thing also happened to players, but for players, they were teleported back 1 frame (or less) later.  But this 1 tick away causes some chunks to visually unload, and breaks a lot of things.

What is done now is that it only fixes the position if the server positions are set - in other words, one of them must not be 0.  (There is a small chance an entity is actually spawned at 0,0,0, but I consider that unlikely enough that it's not worth trying to fix their position in that case).  I also explicitly skip players.

This should be fixed in the next release of the mod, whenever that is (I'm hoping to do one soon).  In the mean time, you should be able to work around the bug by just only downloading in the area once, then disconnecting and reconnecting before starting a second download.

**Closed** 2015-12-24 23:28 UTC
